# tmux config

# Enable mouse support
set -g mouse on

# Status bar customization
set -g status-bg darkblue
set -g status-fg white
set -g status-interval 5
set -g status-right '#{prefix_highlight} | #[fg=cyan]#(whoami)@#h #[default]#(date +"%Y-%m-%d %H:%M")'
set -g status-left '#I #(gitmux "#{pane_current_path}")'
set -g base-index 1
set -g pane-base-index 1

# Pane navigation and resizing
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

bind C-h split-window -h -c "#{pane_current_path}"
bind C-q detach
bind C-v split-window -v -c "#{pane_current_path}"
bind  c  new-window      -c "#{pane_current_path}"

# Reload configuration
bind r source-file ~/.tmux.conf \; display-message "Config reloaded!"

# Plugins
set -g @scroll-speed-num-lines-per-scroll 5

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-notify'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

set -g @plugin 'tmux-plugins/tmux-yank' # Easy clipboard integration
set -g @plugin 'tmux-plugins/tmux-prefix-highlight' # Highlight when prefix is pressed
set -g @plugin 'tmux-plugins/tmux-open' # Open highlighted text with a system command
set -g @plugin 'nhdaly/tmux-better-mouse-mode'

#set -g @plugin 'wfxr/tmux-power'

# Initialize TMUX plugin manager
run '~/.tmux/plugins/tpm/tpm'
