
bindsym XF86AudioRaiseVolume exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ +10%
bindsym XF86AudioLowerVolume exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ -10%
bindsym XF86AudioMute exec --no-startup-id pactl set-sink-mute @DEFAULT_SINK@ toggle
bindsym XF86AudioMicMute exec --no-startup-id pactl set-source-mute @DEFAULT_SOURCE@ toggle

bindsym $mod+Return exec --no-startup-id sh -c 'command -v alacritty && alacritty || notify-send "alacritty not found!"'
bindsym $mod+Shift+Return exec --no-startup-id sh -c 'command -v kitty && kitty || notify-send "kitty not found!"'
bindsym $mod+Control+Return exec --no-startup-id sh -c 'command -v xfce4-terminal && xfce4-terminal || notify-send "xfce4-terminal not found!"'
bindsym $mod+b exec --no-startup-id sh -c 'command -v boomer && boomer || notify-send "boomer not found!"'
bindsym $mod+Control+e exec neoray
bindsym $mod+Shift+q kill
bindsym $mod+d exec --no-startup-id "rofi -modi drun,run -show drun"
bindsym Mod1+Tab exec --no-startup-id "rofi -show window"
